# Generated by Django 5.2.5 on 2026-01-12 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MpSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_cycle', models.CharField(choices=[('monthly', 'Mensal'), ('annual', 'Anual')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('authorized', 'Autorizada'), ('active', 'Ativa'), ('paused', 'Pausada'), ('cancelled', 'Cancelada'), ('expired', 'Expirada'), ('rejected', 'Rejeitada')], default='pending', max_length=20)),
                ('preapproval_id', models.CharField(blank=True, default='', max_length=120)),
                ('init_point', models.URLField(blank=True, default='')),
                ('payer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('reason', models.CharField(blank=True, default='', max_length=140)),
                ('auto_recurring', models.JSONField(blank=True, default=dict)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('last_payment_status', models.CharField(blank=True, default='', max_length=40)),
                ('next_payment_at', models.DateTimeField(blank=True, null=True)),
                ('grace_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mp_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MpWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, default='', max_length=80)),
                ('mp_id', models.CharField(blank=True, default='', max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['topic', 'mp_id'], name='payments_mp_topic_d7fccb_idx')],
            },
        ),
    ]
