# Generated by Django 6.0 on 2026-01-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mpsubscription",
            name="guest_limit",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mpsubscription",
            name="plan_tier",
            field=models.CharField(
                choices=[
                    ("essential", "Essencial"),
                    ("pro", "Pro"),
                    ("master", "Master"),
                ],
                default="essential",
                max_length=20,
            ),
        ),
    ]
