"""
Django settings for TrackerDjangoVersion project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from json import load
import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

dotenv_path = BASE_DIR / ".env"
alt_dotenv_path = Path(__file__).resolve().parent / ".env"
if not dotenv_path.exists() and alt_dotenv_path.exists():
    dotenv_path = alt_dotenv_path
load_dotenv(dotenv_path)


# ------------------------------------------------------------------------------
# Helpers (env)
# ------------------------------------------------------------------------------

def env(name: str, default=None):
    return os.environ.get(name, default)

def env_bool(name: str, default: bool = False) -> bool:
    v = os.environ.get(name)
    if v is None:
        return default
    return v.strip().lower() in ("1", "true", "yes", "on")

def env_list(name: str, default=None):
    v = os.environ.get(name)
    if v is None:
        return default if default is not None else []
    return [x.strip() for x in v.split(",") if x.strip()]

VERSION_FILE = BASE_DIR / "VERSION"
APP_VERSION = env("ITRACKER_VERSION")
if not APP_VERSION:
    try:
        APP_VERSION = VERSION_FILE.read_text(encoding="utf-8").strip()
    except FileNotFoundError:
        APP_VERSION = "0.0.0"


# ------------------------------------------------------------------------------
# Quick-start development settings - unsuitable for production
# ------------------------------------------------------------------------------

# SECURITY WARNING: keep the secret key used in production secret!
# Em produção: export DJANGO_SECRET_KEY="..."
SECRET_KEY = env("DJANGO_SECRET_KEY_TRACKER", "django-insecure-dev-only-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
# Em produção: export DJANGO_DEBUG=0
DEBUG = env_bool("DJANGO_DEBUG", default=True)
SERVE_STATIC = env_bool("DJANGO_SERVE_STATIC", default=DEBUG)
SERVE_MEDIA = env_bool("DJANGO_SERVE_MEDIA", default=DEBUG)

# Em produção: export DJANGO_ALLOWED_HOSTS="3.88.41.192,meudominio.com"
ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", default=["127.0.0.1", "localhost", "3.88.41.192","54.174.218.66"])


# ------------------------------------------------------------------------------
# Application definition
# ------------------------------------------------------------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tracker',
    'assistant',
    'payments',
    'whatsapp_finance',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'tracker.middleware.WorkspaceMiddleware',
]

ROOT_URLCONF = 'TrackerDjangoVersion.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'tracker.context_processors.workspace_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'TrackerDjangoVersion.wsgi.application'


# ------------------------------------------------------------------------------
# Database
# ------------------------------------------------------------------------------

# Em produção: use variáveis de ambiente (mais seguro)
# Ex:
# DB_NAME=tracker
# DB_USER=postgres
# DB_PASSWORD=...
# DB_HOST=127.0.0.1
# DB_PORT=5432
DB_NAME = env("DB_NAME_TRACKER", "")
if DB_NAME:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": DB_NAME,
            "USER": env("DB_USER_TRACKER", "postgres"),
            "PASSWORD": env("DB_PASSWORD_TRACKER", ""),
            "HOST": env("DB_HOST_TRACKER", "localhost"),
            "PORT": env("DB_PORT_TRACKER", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# ------------------------------------------------------------------------------
# Password validation
# ------------------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
    {'NAME': 'tracker.validators.SpecialCharacterValidator'},
]


# ------------------------------------------------------------------------------
# Internationalization
# ------------------------------------------------------------------------------

LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True


# ------------------------------------------------------------------------------
# Static files (CSS, JavaScript, Images)
# ------------------------------------------------------------------------------

# IMPORTANTE: com Nginx servindo /static/ em producao, use '/static/'
STATIC_URL = '/static/'

# Útil em DEV para arquivos em BASE_DIR/static.
# Em produção, o Nginx deve apontar para STATIC_ROOT.
STATICFILES_DIRS = [BASE_DIR / 'static']

# Onde o collectstatic vai juntar tudo
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Serve estaticos em producao sem depender do Nginx


# ------------------------------------------------------------------------------
# Cache (rate limit, sessions, metrics)
# ------------------------------------------------------------------------------

# Em producao, configure REDIS/Memcached via DJANGO_CACHE_BACKEND/LOCATION.
CACHES = {
    "default": {
        "BACKEND": env("DJANGO_CACHE_BACKEND", "django.core.cache.backends.locmem.LocMemCache"),
        "LOCATION": env("DJANGO_CACHE_LOCATION", "itracker-cache"),
    }
}

# Cache TTLs (segundos)
DASHBOARD_CACHE_TTL = int(env("DASHBOARD_CACHE_TTL", "300"))
CHART_CACHE_TTL = int(env("CHART_CACHE_TTL", "300"))

# ------------------------------------------------------------------------------
# Auth redirects
# ------------------------------------------------------------------------------

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'


# ------------------------------------------------------------------------------
# Media
# ------------------------------------------------------------------------------

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ------------------------------------------------------------------------------
# Email (notificacoes)
# ------------------------------------------------------------------------------

EMAIL_BACKEND = env("EMAIL_BACKEND", "")
if not EMAIL_BACKEND:
    use_smtp = (not DEBUG) or bool(env("EMAIL_HOST_USER", ""))
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend" if use_smtp else "django.core.mail.backends.console.EmailBackend"
EMAIL_HOST = env("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(env("EMAIL_PORT", "587"))
EMAIL_HOST_USER = env("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", default=True)
EMAIL_USE_SSL = env_bool("EMAIL_USE_SSL", default=False)
if EMAIL_USE_SSL:
    EMAIL_USE_TLS = False
EMAIL_TIMEOUT = int(env("EMAIL_TIMEOUT", "30"))
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", "iDevelopSystemsNotify@outlook.com")

# ------------------------------------------------------------------------------
# Mercado Pago
# ------------------------------------------------------------------------------

MP_ACCESS_TOKEN = env("MP_ACCESS_TOKEN", "")
MP_PUBLIC_KEY = env("MP_PUBLIC_KEY", "")
MP_BASE_URL = env("MP_BASE_URL", "https://api.mercadopago.com")
MP_CURRENCY = env("MP_CURRENCY", "BRL")
MP_PAYER_EMAIL = env("MP_PAYER_EMAIL", "")
MP_NOTIFICATION_URL = env("MP_NOTIFICATION_URL", "")
MP_PLAN_MONTHLY_AMOUNT = env("MP_PLAN_MONTHLY_AMOUNT", "8.99")
MP_PLAN_ANNUAL_AMOUNT = env("MP_PLAN_ANNUAL_AMOUNT", "71.88")
MP_COLLECTOR_ID = env("MP_COLLECTOR_ID", "")
MP_APP_ID = env("MP_APP_ID", "")
MP_WEBHOOK_TOKEN = env("MP_WEBHOOK_TOKEN", "")
SUBSCRIPTION_GRACE_DAYS = int(env("SUBSCRIPTION_GRACE_DAYS", "7"))
REQUIRE_MANUAL_APPROVAL = env_bool("REQUIRE_MANUAL_APPROVAL", default=not bool(MP_ACCESS_TOKEN))
MP_SIMULATE_PAYMENTS = env_bool("MP_SIMULATE_PAYMENTS", default=False)
TRIAL_DAYS = int(env("TRIAL_DAYS", "7"))

# ------------------------------------------------------------------
# AI quota
# ------------------------------------------------------------------

AI_PLAN_TOKEN_LIMITS = {
    "essential": int(env("AI_ESSENTIAL_TOKEN_LIMIT", env("AI_STARTER_TOKEN_LIMIT", "20000"))),
    "pro": int(env("AI_PRO_TOKEN_LIMIT", "80000")),
    "master": int(env("AI_MASTER_TOKEN_LIMIT", env("AI_TEAM_TOKEN_LIMIT", "200000"))),
}
AI_USAGE_WINDOW_DAYS = int(env("AI_USAGE_WINDOW_DAYS", "30"))

VAPID_PUBLIC_KEY = env("VAPID_PUBLIC_KEY", "")
VAPID_PRIVATE_KEY = env("VAPID_PRIVATE_KEY", "")
VAPID_SUBJECT = env("VAPID_SUBJECT", "mailto:admin@tracker.local")
EMAIL_CONFIRMATION_REQUIRED = env_bool("EMAIL_CONFIRMATION_REQUIRED", default=False)
LOGIN_RATE_LIMIT_ATTEMPTS = int(env("LOGIN_RATE_LIMIT_ATTEMPTS", "5"))
LOGIN_RATE_LIMIT_WINDOW = int(env("LOGIN_RATE_LIMIT_WINDOW", "900"))


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ------------------------------------------------------------------------------
# Hardening (somente em producao)
# ------------------------------------------------------------------------------

if not DEBUG:
    # Se estiver atrás de proxy (Nginx) e HTTPS:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS", default=[])

    # Ative quando tiver HTTPS (certbot) e quiser forçar redirect http->https
    SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", default=False)

    # Recomendações adicionais
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "same-origin"
    SECURE_HSTS_SECONDS = int(env("DJANGO_SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", default=True)
    SECURE_HSTS_PRELOAD = env_bool("DJANGO_SECURE_HSTS_PRELOAD", default=True)
    SESSION_COOKIE_SAMESITE = env("DJANGO_SESSION_SAMESITE", "Lax")
    CSRF_COOKIE_SAMESITE = env("DJANGO_CSRF_SAMESITE", "Lax")



# ------------------------------------------------------------------------------
# Observabilidade e logs estruturados
# ------------------------------------------------------------------------------

LOG_LEVEL = env("DJANGO_LOG_LEVEL", "INFO")
LOG_JSON = env_bool("DJANGO_LOG_JSON", default=not DEBUG)

if LOG_JSON:
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "json": {
                "()": "tracker.logging.JsonFormatter",
            },
        },
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "formatter": "json",
            },
        },
        "root": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
        },
        "loggers": {
            "django": {"level": LOG_LEVEL, "handlers": ["console"], "propagate": False},
        },
    }

# ------------------------------------------------------------------------------
# Sentry (opcional)
# ------------------------------------------------------------------------------

SENTRY_DSN = env("SENTRY_DSN", "")
if SENTRY_DSN:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration

        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[DjangoIntegration()],
            traces_sample_rate=float(env("SENTRY_TRACES_SAMPLE_RATE", "0.05")),
            environment=env("SENTRY_ENVIRONMENT", "production"),
        )
    except Exception:
        pass

# ------------------------------------------------------------------------------
# WhatsApp Finance (Twilio)
# ------------------------------------------------------------------------------

# WhatsApp Cloud API (Meta)
META_WA_BASE_URL = env("META_WA_BASE_URL", "https://graph.facebook.com")
META_WA_API_VERSION = env("META_WA_API_VERSION", "v19.0")
META_WA_ACCESS_TOKEN = env("META_WA_ACCESS_TOKEN", "")
META_WA_WABA_ID = env("META_WA_WABA_ID", "")
META_WA_PHONE_NUMBER_ID = env("META_WA_PHONE_NUMBER_ID", "")
META_WA_VERIFY_TOKEN = env("META_WA_VERIFY_TOKEN", "")
META_WA_APP_SECRET = env("META_WA_APP_SECRET", "")
META_WA_VALIDATE_SIGNATURE = env_bool("META_WA_VALIDATE_SIGNATURE", True)
META_WA_FETCH_MEDIA = env_bool("META_WA_FETCH_MEDIA", True)
META_WA_DISPLAY_NUMBER = env("META_WA_DISPLAY_NUMBER", "")

# Twilio (legado)
TWILIO_ACCOUNT_SID = env("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN = env("TWILIO_AUTH_TOKEN", "")
TWILIO_WHATSAPP_NUMBER = env("TWILIO_WHATSAPP_NUMBER", "")
WHATSAPP_VALIDATE_TWILIO = env_bool("WHATSAPP_VALIDATE_TWILIO", False)
WHATSAPP_FEATURE_ENABLED = env_bool("WHATSAPP_FEATURE_ENABLED", False)
WHATSAPP_TRANSCRIBE_PROVIDER = env("WHATSAPP_TRANSCRIBE_PROVIDER", "none")  # none|whisper|google
WHATSAPP_WHISPER_MODEL = env("WHATSAPP_WHISPER_MODEL", "base")
WHATSAPP_OCR_ENABLED = env_bool("WHATSAPP_OCR_ENABLED", True)
WHATSAPP_CONFIRMATION_THRESHOLD = env("WHATSAPP_CONFIRMATION_THRESHOLD", 1000)
WHATSAPP_AUTO_CONFIRM_BELOW_THRESHOLD = env_bool("WHATSAPP_AUTO_CONFIRM_BELOW_THRESHOLD", False)
WHATSAPP_CREATE_MISSING_CATEGORIES = env_bool("WHATSAPP_CREATE_MISSING_CATEGORIES", True)
