# Generated by Django 5.2.10 on 2026-01-21 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tracker", "0029_pricingconfig_plan_prices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone_number", models.CharField(max_length=32, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="whatsapp_profile", to=settings.AUTH_USER_MODEL)),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="whatsapp_profiles", to="tracker.workspace")),
            ],
            options={
                "indexes": [models.Index(fields=["phone_number"], name="whatsapp_fi_phone_n_1ff0f9_idx")],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message_sid", models.CharField(blank=True, default="", max_length=120)),
                ("direction", models.CharField(choices=[("in", "Entrada"), ("out", "Saida")], default="in", max_length=8)),
                ("from_number", models.CharField(blank=True, default="", max_length=32)),
                ("to_number", models.CharField(blank=True, default="", max_length=32)),
                ("body", models.TextField(blank=True, default="")),
                ("media_url", models.URLField(blank=True, default="")),
                ("media_type", models.CharField(blank=True, default="", max_length=80)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="whatsapp_messages", to=settings.AUTH_USER_MODEL)),
                ("workspace", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="whatsapp_messages", to="tracker.workspace")),
            ],
            options={
                "indexes": [models.Index(fields=["message_sid", "created_at"], name="whatsapp_fi_message_3df52a_idx")],
            },
        ),
        migrations.CreateModel(
            name="ParsedTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(blank=True, default="", max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("type", models.CharField(choices=[("income", "Entrada"), ("expense", "Saida")], max_length=10)),
                ("date", models.DateField()),
                ("category_label", models.CharField(blank=True, default="", max_length=120)),
                ("requires_confirmation", models.BooleanField(default=False)),
                ("status", models.CharField(choices=[("pending", "Pendente"), ("confirmed", "Confirmado"), ("rejected", "Rejeitado"), ("corrected", "Corrigido")], default="pending", max_length=20)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("category", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="whatsapp_parsed_transactions", to="tracker.category")),
                ("source_message", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="parsed_entries", to="whatsapp_finance.whatsappmessage")),
                ("transaction", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="whatsapp_parsed_transactions", to="tracker.transaction")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="whatsapp_parsed_transactions", to=settings.AUTH_USER_MODEL)),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="whatsapp_parsed_transactions", to="tracker.workspace")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["workspace", "status"], name="whatsapp_fi_workspa_0f9c43_idx"),
                    models.Index(fields=["user", "created_at"], name="whatsapp_fi_user_id_34f308_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CategoryPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("keyword", models.CharField(max_length=80)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="whatsapp_category_preferences", to="tracker.category")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="whatsapp_category_preferences", to=settings.AUTH_USER_MODEL)),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="whatsapp_category_preferences", to="tracker.workspace")),
            ],
            options={
                "indexes": [models.Index(fields=["workspace", "keyword"], name="whatsapp_fi_workspa_9f363a_idx")],
                "unique_together": {("user", "workspace", "keyword")},
            },
        ),
    ]
