# Generated by Django 6.0 on 2026-01-22 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='categorypreference',
            new_name='whatsapp_fi_workspa_e38eff_idx',
            old_name='whatsapp_fi_workspa_9f363a_idx',
        ),
        migrations.RenameIndex(
            model_name='parsedtransaction',
            new_name='whatsapp_fi_workspa_a01836_idx',
            old_name='whatsapp_fi_workspa_0f9c43_idx',
        ),
        migrations.RenameIndex(
            model_name='parsedtransaction',
            new_name='whatsapp_fi_user_id_ecf429_idx',
            old_name='whatsapp_fi_user_id_34f308_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappmessage',
            new_name='whatsapp_fi_message_0b768b_idx',
            old_name='whatsapp_fi_message_3df52a_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappprofile',
            new_name='whatsapp_fi_phone_n_886f77_idx',
            old_name='whatsapp_fi_phone_n_1ff0f9_idx',
        ),
    ]
