from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from . import views
from . import views_pdf

app_name = 'tracker'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('register/guest/', views.register_guest_view, name='register_guest'),
    path('register/verify/<uidb64>/<token>/', views.verify_email, name='verify_email'),
    path('password-reset/', views.TrackerPasswordResetView.as_view(
        template_name='registration/password_reset_form.html',
        email_template_name='registration/password_reset_email.txt',
        html_email_template_name='registration/password_reset_email.html',
        subject_template_name='registration/password_reset_subject.txt',
        success_url=reverse_lazy('tracker:password_reset_done'),
    ), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/password_reset_done.html',
    ), name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html',
        success_url=reverse_lazy('tracker:password_reset_complete'),
    ), name='password_reset_confirm'),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html',
    ), name='password_reset_complete'),
    path('help/', views.help_page, name='help'),
    path('termos/', views.terms_page, name='terms'),
    path('privacidade/', views.privacy_page, name='privacy'),
    path('perfil/', views.profile_edit, name='profile_edit'),
    path('perfil/exportar/', views.export_my_data, name='export_my_data'),
    path('perfil/excluir/', views.account_delete_request, name='account_delete_request'),
    path('perfil/excluir-definitivo/', views.account_delete_self, name='account_delete_self'),
    path('contato/', views.contact_admin, name='contact_admin'),
    path('notificacoes/', views.notifications_center, name='notifications'),
    path('notificacoes/<int:pk>/lida/', views.notifications_mark_read, name='notifications_mark_read'),
    path('notificacoes/<int:pk>/excluir/', views.notifications_delete, name='notifications_delete'),
    path('notificacoes/lidas/', views.notifications_mark_all, name='notifications_mark_all'),
    path('notificacoes/enviar/', views.notifications_broadcast, name='notifications_broadcast'),
    path('notificacoes/push/subscribe/', views.push_subscribe, name='push_subscribe'),
    path('notificacoes/push/unsubscribe/', views.push_unsubscribe, name='push_unsubscribe'),
    path('alertas/orcamento/', views.category_budget_create, name='category_budget_create'),
    path('alertas/orcamento/<int:pk>/excluir/', views.category_budget_delete, name='category_budget_delete'),
    path('alertas/meta/', views.balance_goal_create, name='balance_goal_create'),
    path('alertas/meta/<int:pk>/excluir/', views.balance_goal_delete, name='balance_goal_delete'),
    path('workspaces/', views.workspace_overview, name='workspace_overview'),
    path('workspaces/request/', views.workspace_request_access, name='workspace_request_access'),
    path('workspaces/select/', views.workspace_select, name='workspace_select'),
    path('workspaces/<slug:slug>/switch/', views.workspace_switch, name='workspace_switch'),
    path('workspaces/members/', views.workspace_members, name='workspace_members_current'),
    path('workspaces/<slug:slug>/members/', views.workspace_members, name='workspace_members'),
    path('workspaces/convites/', views.workspace_invite, name='workspace_invite_current'),
    path('workspaces/<slug:slug>/convites/', views.workspace_invite, name='workspace_invite'),
    path('workspaces/<slug:slug>/excluir/', views.workspace_delete, name='workspace_delete'),
    path('workspaces/<slug:slug>/sair/', views.workspace_leave, name='workspace_leave'),
    path('workspaces/<slug:slug>/members/<int:member_id>/remove/', views.workspace_member_remove, name='workspace_member_remove'),
    path('workspaces/<slug:slug>/members/<int:member_id>/update/', views.workspace_member_update, name='workspace_member_update'),
    path('workspaces/<slug:slug>/requests/<int:req_id>/<str:decision>/', views.workspace_request_action, name='workspace_request_action'),
    path('workspaces/invites/<int:invite_id>/<str:decision>/', views.workspace_invite_action, name='workspace_invite_action'),
    path('super/overview/', views.superuser_overview, name='superuser_overview'),
    path('super/users/', views.user_admin_list, name='user_admin_list'),
    path('super/users/novo/', views.user_admin_form, name='user_admin_create'),
    path('super/users/<int:pk>/', views.user_admin_form, name='user_admin_edit'),
    path('super/users/<int:pk>/ver/', views.user_admin_detail, name='user_admin_detail'),
    path('super/users/<int:pk>/status/', views.user_admin_status, name='user_admin_status'),
    path('super/users/<int:pk>/excluir/', views.user_admin_delete, name='user_admin_delete'),
    path('super/convites/', views.subscription_invite_list, name='subscription_invite_list'),
    path('super/convites/<int:pk>/<str:action>/', views.subscription_invite_action, name='subscription_invite_action'),
    path('app/', views.dashboard, name='dashboard'),
    path('api/chart-data/', views.chart_data, name='chart_data'),
    path('transacoes/', views.transactions_list, name='transactions_list'),
    path('transacoes/acoes/', views.transactions_bulk_update, name='transactions_bulk_update'),
    path('transacoes/nova/', views.transaction_create, name='transaction_create'),
    path('transacoes/<int:pk>/editar/', views.transaction_update, name='transaction_update'),
    path('transacoes/<int:pk>/excluir/', views.transaction_delete, name='transaction_delete'),
    path('transacoes/desfazer/', views.transaction_undo_delete, name='transaction_undo_delete'),
    path('transacoes/<int:pk>/selecionar/', views.transaction_toggle_selected, name='transaction_toggle_selected'),
    path('transacoes/<int:pk>/tipo/', views.transaction_toggle_type, name='transaction_toggle_type'),
    path('transacoes/importar/', views.transaction_import, name='transaction_import'),
    path('transacoes/importar-pdf/', views_pdf.transaction_import_pdf, name='transaction_import_pdf'),
    path('tarefas/', views.tasks_list, name='tasks_list'),
    path('tarefas/acoes/', views.tasks_bulk_update, name='tasks_bulk_update'),
    path('tarefas/nova/', views.task_create, name='task_create'),
    path('tarefas/<int:pk>/editar/', views.task_update, name='task_update'),
    path('tarefas/<int:pk>/excluir/', views.task_delete, name='task_delete'),
    path('tarefas/desfazer/', views.task_undo_delete, name='task_undo_delete'),
    path('tarefas/<int:pk>/etapas/<int:step_id>/', views.task_step_detail, name='task_step_detail'),
    path('tarefas/<int:pk>/etapas/nova/', views.task_step_add, name='task_step_add'),
    path('tarefas/<int:pk>/etapas/<int:step_id>/editar/', views.task_step_update, name='task_step_update'),
    path('tarefas/<int:pk>/etapas/<int:step_id>/toggle/', views.task_step_toggle, name='task_step_toggle'),
    path('tarefas/<int:pk>/etapas/<int:step_id>/excluir/', views.task_step_delete, name='task_step_delete'),
    path('tarefas/<int:pk>/status-toggle/', views.task_toggle_status, name='task_toggle_status'),
    path('tarefas/<int:pk>/selecionar/', views.task_toggle_selected, name='task_toggle_selected'),
    path('categorias/', views.categories_list, name='categories_list'),
    path('categorias/<int:pk>/editar/', views.category_edit, name='category_edit'),
    path('categorias/<int:pk>/excluir/', views.category_delete, name='category_delete'),
]
