# Generated by Django 5.2.5 on 2026-01-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_task_progress_task_responsible_taskstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='responsible_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
