# Generated by Django 5.2.5 on 2026-01-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_task_responsible_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstep',
            name='responsible',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='taskstep',
            name='responsible_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
