# Generated by Django 6.0 on 2026-01-05 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_category_workspace_userprofile'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='uniq_category_workspace_name',
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('workspace', 'name')},
        ),
    ]
