# Generated by Django 6.0 on 2026-01-05 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_remove_category_uniq_category_workspace_name_and_more'),
        ('tracker', '0008_workspacemembership_can_edit_tasks'),
    ]

    operations = [
    ]
