# Generated by Django 5.2.5 on 2026-01-07 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_auto_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='category',
            new_name='tracker_cat_workspa_47aec5_idx',
            old_name='tracker_cat_workspace_name_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tracker_tas_workspa_3b5ad8_idx',
            old_name='tracker_task_workspace_status_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tracker_tas_workspa_de67b4_idx',
            old_name='tracker_task_workspace_due_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='tracker_tra_workspa_928a6b_idx',
            old_name='tracker_tx_workspace_date_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='tracker_tra_workspa_1c8c4a_idx',
            old_name='tracker_tx_workspace_type_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='tracker_tra_categor_f5e906_idx',
            old_name='tracker_tx_category_date_idx',
        ),
        migrations.RenameIndex(
            model_name='workspacemembership',
            new_name='tracker_wor_workspa_e987b1_idx',
            old_name='tracker_membership_ws_user_idx',
        ),
    ]
