# Generated by Django 5.2.5 on 2026-01-07 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def seed_profiles(apps, schema_editor):
    UserModel = apps.get_model(settings.AUTH_USER_MODEL.split(".")[0], settings.AUTH_USER_MODEL.split(".")[1])
    Profile = apps.get_model("tracker", "UserProfile")
    now = timezone.now()
    for user in UserModel.objects.all():
        profile, created = Profile.objects.get_or_create(user=user)
        if created or not profile.is_approved:
            profile.is_approved = True
            profile.approved_at = now
            profile.save(update_fields=["is_approved", "approved_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_rename_tracker_cat_workspace_name_idx_tracker_cat_workspa_47aec5_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_expires',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(seed_profiles, migrations.RunPython.noop),
    ]
