# Generated by Django 5.2.5 on 2026-01-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_userprofile_is_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='payment_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payment_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(choices=[('starter', 'B\u00e1sico'), ('pro', 'Pro'), ('team', 'Equipe')], default='starter', max_length=20),
        ),
    ]
