# Generated by Django 6.0 on 2026-01-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_notifications_and_alerts'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='balancegoal',
            new_name='tracker_bal_workspa_62b22e_idx',
            old_name='tracker_bal_worksp_6fb244_idx',
        ),
        migrations.RenameIndex(
            model_name='categorybudget',
            new_name='tracker_cat_workspa_0db42e_idx',
            old_name='tracker_cat_worksp_1af38d_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='tracker_not_user_id_4fce11_idx',
            old_name='tracker_not_user_re_66e6e0_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='tracker_not_workspa_a737cd_idx',
            old_name='tracker_not_worksp_8a2bde_idx',
        ),
        migrations.RenameIndex(
            model_name='pushsubscription',
            new_name='tracker_pus_user_id_0a4edb_idx',
            old_name='tracker_pus_user_upd_0be5a0_idx',
        ),
        migrations.AlterField(
            model_name='balancegoal',
            name='direction',
            field=models.CharField(choices=[('min', 'Mínimo'), ('max', 'Máximo')], default='min', max_length=10),
        ),
    ]
