# Generated by Django 5.2.5 on 2026-01-11 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_task_completed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SubscriptionInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('plan_cycle', models.CharField(choices=[('monthly', 'Mensal'), ('annual', 'Anual')], default='monthly', max_length=20)),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionInviteUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='tracker.subscriptioninvite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_invites_used', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetricEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'Login: sucesso'), ('login_failed', 'Login: falha'), ('login_blocked', 'Login: bloqueado'), ('signup', 'Cadastro'), ('invite_sent', 'Convite enviado'), ('invite_accepted', 'Convite aceito'), ('payment_confirmed', 'Pagamento confirmado'), ('subscription_renewed', 'Assinatura renovada'), ('ai_request', 'IA: requisição'), ('data_export', 'Exportação de dados'), ('deletion_request', 'Solicitação de exclusão'), ('password_reset', 'Recuperação de senha')], max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_events', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_events', to='tracker.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='tracker_met_event_t_441800_idx'), models.Index(fields=['user', 'created_at'], name='tracker_met_user_id_be39b0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='subscriptioninvite',
            index=models.Index(fields=['code', 'is_active'], name='tracker_sub_code_767b35_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioninviteuse',
            index=models.Index(fields=['invite', 'used_at'], name='tracker_sub_invite__cd8dba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptioninviteuse',
            unique_together={('invite', 'user')},
        ),
    ]
