# Generated by Django 6.0 on 2026-01-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_userprofile_deletion_requested_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_active', models.BooleanField(default=True)),
                ('promo_limit', models.PositiveIntegerField(default=100)),
                ('promo_monthly_price', models.DecimalField(decimal_places=2, default=8.99, max_digits=8)),
                ('promo_annual_price', models.DecimalField(decimal_places=2, default=5.99, max_digits=8)),
                ('regular_monthly_price', models.DecimalField(decimal_places=2, default=14.99, max_digits=8)),
                ('regular_annual_price', models.DecimalField(decimal_places=2, default=9.99, max_digits=8)),
                ('promo_label', models.CharField(default='Promo\u00e7\u00e3o de lan\u00e7amento', max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configura\u00e7\u00e3o de pre\u00e7os',
                'verbose_name_plural': 'Configura\u00e7\u00f5es de pre\u00e7os',
            },
        ),
    ]
