# Generated by Django 6.0 on 2026-01-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0024_taskstep_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trial_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
