# Generated by Django 5.2.5 on 2026-01-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0025_userprofile_trial_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
