# Generated by Django 6.0 on 2026-01-21 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0026_task_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptioninvite",
            name="plan_tier",
            field=models.CharField(
                choices=[
                    ("essential", "Essencial"),
                    ("pro", "Pro"),
                    ("master", "Master"),
                ],
                default="essential",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="responsible",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responsible_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="master_guest_limit",
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="plan",
            field=models.CharField(
                choices=[
                    ("essential", "Essencial"),
                    ("pro", "Pro"),
                    ("master", "Master"),
                ],
                default="essential",
                max_length=20,
            ),
        ),
    ]
