# Generated by Django 5.2.10 on 2026-01-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0027_subscriptioninvite_plan_tier_transaction_responsible_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingconfig",
            name="pro_multiplier",
            field=models.DecimalField(decimal_places=2, default=1.40, max_digits=5),
        ),
        migrations.AddField(
            model_name="pricingconfig",
            name="master_multiplier",
            field=models.DecimalField(decimal_places=2, default=1.90, max_digits=5),
        ),
    ]
