# Generated by Django 5.2.10 on 2026-01-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0028_pricingconfig_multipliers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricingconfig",
            name="pro_multiplier",
        ),
        migrations.RemoveField(
            model_name="pricingconfig",
            name="master_multiplier",
        ),
        migrations.AddField(
            model_name="pricingconfig",
            name="promo_monthly_pro",
            field=models.DecimalField(decimal_places=2, default=12.59, max_digits=8),
        ),
        migrations.AddField(
            model_name="pricingconfig",
            name="promo_annual_pro",
            field=models.DecimalField(decimal_places=2, default=8.39, max_digits=8),
        ),
        migrations.AddField(
            model_name="pricingconfig",
            name="promo_monthly_master",
            field=models.DecimalField(decimal_places=2, default=17.08, max_digits=8),
        ),
        migrations.AddField(
            model_name="pricingconfig",
            name="promo_annual_master",
            field=models.DecimalField(decimal_places=2, default=11.38, max_digits=8),
        ),
        migrations.AddField(
            model_name="pricingconfig",
            name="regular_monthly_pro",
            field=models.DecimalField(decimal_places=2, default=20.99, max_digits=8),
        ),
        migrations.AddField(
            model_name="pricingconfig",
            name="regular_annual_pro",
            field=models.DecimalField(decimal_places=2, default=13.99, max_digits=8),
        ),
        migrations.AddField(
            model_name="pricingconfig",
            name="regular_monthly_master",
            field=models.DecimalField(decimal_places=2, default=28.48, max_digits=8),
        ),
        migrations.AddField(
            model_name="pricingconfig",
            name="regular_annual_master",
            field=models.DecimalField(decimal_places=2, default=18.98, max_digits=8),
        ),
    ]
