# Generated by Django 6.0 on 2026-01-22 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0030_task_responsible_user'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='task',
            new_name='tracker_tas_workspa_adc600_idx',
            old_name='tracker_ta_workspa_5d6f4a_idx',
        ),
    ]
