# Generated by Django 6.0 on 2026-01-25 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0025_task_categories'),
        ('tracker', '0031_rename_tracker_ta_workspa_5d6f4a_idx_tracker_tas_workspa_adc600_idx'),
    ]

    operations = [
    ]
