# Generated by Django 5.2.5 on 2026-01-25 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0032_merge_20260124_2131'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='taskcategory',
            new_name='tracker_tas_workspa_3ffdf2_idx',
            old_name='taskcategory_workspace_name_idx',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='master_guest_limit_pending',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
