# Generated by Django 5.2.5 on 2026-01-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0033_rename_taskcategory_workspace_name_idx_tracker_tas_workspa_3ffdf2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='grace_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
