# Generated by Django 5.2.5 on 2026-02-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0036_userprofile_sidebar_hover_expand'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_rotated_openai', models.DateField(blank=True, null=True)),
                ('last_rotated_twilio', models.DateField(blank=True, null=True)),
                ('last_rotated_mp', models.DateField(blank=True, null=True)),
                ('last_rotated_whatsapp', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de segurança',
                'verbose_name_plural': 'Configurações de segurança',
            },
        ),
    ]
